apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sky-ladder-prod
  name: sky-ladder-prod
  namespace: ops-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sky-ladder-prod
  template:
    metadata:
      labels:
        app: sky-ladder-prod
    spec:
      serviceAccountName: ladder-reg-role-account
      containers:
        - command:
          - ./ladder
          args:
            - proxy
            - --addr
            - 0.0.0.0:8080
            # - --auth # 为空，直接跳过校验
            - --registry # 从远程获取k8s信息
            - remote
            - --registryConfig # 远程地址，测试直接去sidecar获取即可
            - 127.0.0.1:8083
            - --sidecar  # 获取k8s pod信息
            - 127.0.0.1:8083
            - --agip  # 直接返回写死的agent
            - "172.19.0.2"
            - --agp
            - "20077"
          env:
            - name: GODEBUG
              value: gctrace=1,madvdontneed=1
          image: proxyImg:latest
          imagePullPolicy: IfNotPresent
          name: proxy
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
        - args:
            - mock
            - --ip
            - "172.19.0.2"
            - --id
            - 7ddfcdbc7ed74
          command:
            - ./ladder
          image: proxyImg:latest
          imagePullPolicy: IfNotPresent
          name: reg
          ports:
            - containerPort: 8083
              protocol: TCP
              name: http
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /apps/logs/ops/sky-ladder-proxy/audit/
            type: DirectoryOrCreate
          name: volume-data